---
title: "Data Coding pt. 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
require("ncdf4")
library(sf)
library(raster)
library(rgdal)
library(stringr)
library(rgeos)
library(stargazer)
library(survey)
```

```{r}
IPUMS_DHS<-read.csv("DHS_2014/IPUMS_DHS_v3 (2).csv", na.strings=c("9994", "9995", "9996", "9997", "9998", "9999", "-998"))
```

```{r}
tbl_df <- tbl_df(IPUMS_DHS)
class(tbl_df)
tbl_df
```

```{r}
#Remove NAs
IPUMS_DHS$RESIDENT<-na_if(IPUMS_DHS$RESIDENT, "8")

IPUMS_DHS$HHEADSEXHH<- na_if(IPUMS_DHS$HHEADSEXHH, "8")
IPUMS_DHS$HHEADSEXHH<- na_if(IPUMS_DHS$HHEADSEXHH, "9")

IPUMS_DHS$FLOOR<- na_if(IPUMS_DHS$FLOOR, "996")
IPUMS_DHS$FLOOR<- na_if(IPUMS_DHS$FLOOR, "997")
IPUMS_DHS$FLOOR<- na_if(IPUMS_DHS$FLOOR, "998")
IPUMS_DHS$FLOOR<- na_if(IPUMS_DHS$FLOOR, "999")


IPUMS_DHS$WEALTHQ<- na_if(IPUMS_DHS$WEALTHQ, "8")

IPUMS_DHS$EDUCLVL<- na_if(IPUMS_DHS$EDUCLVL, "8")

IPUMS_DHS$KIDCURAGE<- na_if(IPUMS_DHS$KIDCURAGE, "98")
IPUMS_DHS$KIDCURAGE<- na_if(IPUMS_DHS$KIDCURAGE, "99")

IPUMS_DHS$KIDAGEMO<-na_if(IPUMS_DHS$KIDAGEMO, "99")
IPUMS_DHS$KIDAGEMO<-na_if(IPUMS_DHS$KIDAGEMO, "98")
```

#RE-coding variables into aggregate categories

```{r}
#(1)=stunted < -2 z-scores, (0)=not stunted >2 z-scores (data has no decimals in it, -2=-200)
IPUMS_DHS$binary_HWHAZWHO<-ifelse(IPUMS_DHS$HWHAZWHO< -200, 1, 0)

#1=Natural/Rudimentary, #0=Finisheed
IPUMS_DHS$floor_type<-ifelse(IPUMS_DHS$FLOOR<300, 1, 0)

#0=Piped Water, #1= Well Water/Surface Water #2=Purchased from supplier #3=Other
IPUMS_DHS$drinking_water<-ifelse(IPUMS_DHS$DRINKWTR<2000, 0, IPUMS_DHS$DRINKWTR)
IPUMS_DHS$drinking_water<-ifelse(IPUMS_DHS$DRINKWTR>2000 & IPUMS_DHS$DRINKWTR<5000, 1, IPUMS_DHS$drinking_water)
IPUMS_DHS$drinking_water<-ifelse(IPUMS_DHS$DRINKWTR>4999 & IPUMS_DHS$DRINKWTR<6000, 2, IPUMS_DHS$drinking_water)
IPUMS_DHS$drinking_water<-ifelse(IPUMS_DHS$DRINKWTR>5999, 3, IPUMS_DHS$drinking_water)

#LIVELIHOODS: #1=Pastoralist, #2=Agro-Past, #3= small farmer, #4=large farmer


#0= No Facility, #1= Flush, #2= Non-flush, #3=Other
IPUMS_DHS$Toilet_type<-ifelse(IPUMS_DHS$TOILETTYPE>4999, 3, IPUMS_DHS$TOILETTYPE)
IPUMS_DHS$Toilet_type<-ifelse(IPUMS_DHS$TOILETTYPE>2000 & IPUMS_DHS$TOILETTYPE<4999, 2, IPUMS_DHS$Toilet_type)
IPUMS_DHS$Toilet_type<-ifelse(IPUMS_DHS$TOILETTYPE<2000 & IPUMS_DHS$TOILETTYPE>0, 1, IPUMS_DHS$Toilet_type)

#0=not a twin, #1=Twin or multiple
IPUMS_DHS$Kidtwin<-ifelse(IPUMS_DHS$KIDTWIN>10, 0, 1)

#0=birth order up to 10, #1= birth order 11+
IPUMS_DHS$Kidbord<- ifelse(IPUMS_DHS$KIDBORD<10, 0, 1)

IPUMS_DHS$Kidsex<-ifelse(IPUMS_DHS$KIDSEX<2, 0, 1)
```

```{r}
#Convert types of variables
IPUMS_DHS<-IPUMS_DHS%>%
    mutate(URBAN = as.factor(URBAN)) %>% 
    mutate(EDUCLVL = as.factor(EDUCLVL)) %>% 
    mutate(floor_type = as.factor(floor_type))%>%
    mutate(drinking_water=as.factor(drinking_water))%>%
    mutate(HHEADSEXHH=as.factor(HHEADSEXHH))%>%
    mutate(KIDAGEMO=as.numeric(KIDAGEMO))%>%
    mutate(WEIGHTFEM=as.numeric(WEIGHTFEM))%>%
    mutate(HEIGHTFEM=as.numeric(HEIGHTFEM))%>%
    mutate(Toilet_type=as.factor(Toilet_type))%>%
    mutate(Kidbord=as.numeric(Kidbord))%>%
    mutate(binary_HWHAZWHO=as.factor(binary_HWHAZWHO))%>%
    mutate(WEALTHQ=as.factor(WEALTHQ))%>%
    mutate(Kidtwin=as.factor(Kidtwin))%>%
    mutate(HWWEIGHT=as.numeric(HWWEIGHT))%>%
    mutate(Kidsex=as.factor(Kidsex))%>%
    mutate(AGE=as.numeric(AGE))%>%
    mutate(Kidbirthmo=as.numeric(KIDBIRTHMO))%>%
    mutate(Kidbirthyr=as.numeric(KIDBIRTHYR))%>%
    mutate(Kid_age= as.numeric(KIDCURAGE))%>%
    mutate(Kid_dobcmc=as.numeric(KIDDOBCMC))%>%
    mutate(DHS_Livelihood=as.factor(DHS_LIVELIHOOD))%>%
    mutate(Livelihood=as.factor(LVLHD))
```



```{r}
#Here is my climate variable with 10 degree buffer.. this gets a little crazy

file_list <- list.files("TerraClimate", full.names = TRUE) ## Gets the names of all files in working directory
file_list <- file_list[str_sub(file_list, -3, -1) == ".nc"] ## Gets only the netCDF files

## Reading in the point data
poly1=readOGR("DHS_2014/KEGE71FL.shp") 
poly1 <- poly1[poly1@coords[,1] > 0,] ## Removing points at 0,0
poly2_pts = spTransform(poly1, CRS("+init=epsg:3395")) ## Re-projecting polygon to match raster projection. You'll need to make sure this is a good projection for Kenya

## Buffering points to polygons by 10km
poly2=as(gBuffer(poly2_pts, width = 10000, byid = T), "SpatialPolygonsDataFrame") #This buffers your input polygon by a certain distance

## Create a loop to iterate through each netcdf file you are working with and
  ## Do all of the lines below. That will create a "list" for each file that
  ## you will then use to calculate summary statistics later.
new_list <- list()
for(i in 1:length(file_list)){
  #rfe_2013 <- raster("TAMSAT/rfe2013_MAM_seas.v3 (1).nc")
  clim_raster <- raster(file_list[i])
  clim_raster <- crop(clim_raster, extend(extent(poly1), 0.5))
  test <- projectRaster(clim_raster, crs = poly2@proj4string)
  #plot(test)
  #plot(poly2, add = T)
  
  new_list[[i]] <- extract(test, poly2)
  print(paste("File", i, "out of", length(file_list)))
}

saveRDS(new_list, "ClimateExtractions.rds")

#summary(ClimateExtractions) 

  # through each climate file you are looking at for each month
  # It then pulls out summary statistics from square areas intersecting the polygondefined

 # in poly1
all_data = list(); count = 1
for(i in list.files()){
  spatial_files = list.files(file.path(getwd(), i))
  spatial_files = subset(spatial_files, str_sub(spatial_files,-7,-1)=="rfe_2013")
  ## Note the "bil.bil" in the above line refers to the file extension of the rasters.
  for(j in spatial_files){
    name = paste(i, "_",str_sub(j, -14,-9), sep = "")
    test = file.path(getwd(),i,j)
    test_grid =  raster(test)
    all_data[[count]] = as.matrix(crop(test_grid, poly2))
    names(all_data)[[count]] = name
    count = count+1
    cat(paste("file", count, "\n"))
  }
}

saveRDS(all_data, "Multilevel Modeling/rfe_buffer.rds")
poly2@data <- poly@data$
```


```{r}
mat_list <- list()
for(i in 1:length(new_list)){
  for(j in 1:length(new_list[[1]])){
    if(i == 1){mat_list[[j]] = matrix(-999, nrow = length(new_list),
                                      ncol = length(new_list[[i]][[j]]))}
    mat_list[[j]][i,] <- new_list[[i]][[j]]
  }
}


summarize <- function(matrix_grid, normalize = c(TRUE, FALSE)){
  matrix_grid[matrix_grid == -999] <- NA
  if(normalize == TRUE){matrix_grid <- scale(matrix_grid)}
  site_summary <- rowMeans(matrix_grid, na.rm = T)
  return(site_summary)
}

summarized <- lapply(mat_list, summarize, normalize = T) #z-scores
summarized_raw <- lapply(mat_list, summarize, normalize = F) #raw 

last_matrix <- matrix(-999, nrow = length(new_list[[1]]), ncol = length(new_list))
for(i in 1:length(summarized)){
  last_matrix[i,] <- summarized[[i]]
}

last_matrix_raw <- matrix(-999, nrow = length(new_list[[1]]), ncol = length(new_list))
for(i in 1:length(summarized)){
  last_matrix_raw[i,] <- summarized_raw[[i]]
}

last_matrix <- as.data.frame(last_matrix)
last_matrix_raw <- as.data.frame(last_matrix_raw)


colnames(last_matrix) <- paste("Year", as.character(c(1985:2014)), sep = "_") #z-score
colnames(last_matrix_raw) <- paste("RawYear", as.character(c(1985:2014)), sep = "_") #raw score

poly2_pts@data <- cbind(poly2_pts@data, last_matrix, last_matrix_raw)

writeOGR(poly2_pts, dsn = "/Users/sarahposner/Documents/Multilevel Modeling/Summarized Data", layer = "Kyle_Code",
         driver = "ESRI Shapefile", overwrite_layer = T)
plot(poly2_pts)

my_df <- poly2_pts@data
my_df <- cbind(my_df,coordinates(poly2_pts))
```

```{r}
#full join of survey data with climate variables based on 'DHSID'
final_df<- inner_join(IPUMS_DHS, my_df)
#summary(final_df)
```

##Drought and Wetness Variables
#Calculated by the z-score of the climate water deficit variable into 2 measures: wetness and dryness

```{r}
#DRY  
#0-3= "0" (not dry), -1-0 = "1" (dry), -2-(-1)= "2" (more dry), -3 and less="3" (most dry)


#2009
final_df$Dry_Year2009<-ifelse(final_df$Year_2009>=0 & final_df$Year_2009<=3, "0",ifelse(final_df$Year_2009>=-1 & final_df$Year_2009<=-0, "1", ifelse(final_df$Year_2009>=-2 & final_df$Year_2009<=-1, "2", ifelse(final_df$Year_2009>=-3, "3"))))
final_df$Dry_2009<-as.factor(final_df$Dry_2009) 

#2010
final_df$Dry_2010<-ifelse(final_df$Year_2010>=0 & final_df$Year_2010<=3, "0", ifelse(final_df$Year_2010>=-1 & final_df$Year_2010<=-0, "1", ifelse(final_df$Year_2010>=-2 & final_df$Year_2010<=-1, "2", ifelse(final_df$Year_2011>=-3, "3"))))
final_df$Dry_2010<-as.factor(final_df$Dry_2010) 
                                
#2011                              
final_df$Dry_2011<-ifelse(final_df$Year_2011>=0 & final_df$Year_2011<=3, "0", ifelse(final_df$Year_2011>=-1 & final_df$Year_2011<=-0, "1", ifelse(final_df$Year_2011>=-2 & final_df$Year_2011<=-1, "2", ifelse(final_df$Year_2011>=-3, "3"))))
final_df$Dry_2011<-as.factor(final_df$Dry_2011) 

#2012
final_df$Dry_2012<-ifelse(final_df$Year_2012>=0 & final_df$Year_2012<=3, "0", ifelse(final_df$Year_2012>=-1 & final_df$Year_2012<=-0, "1", ifelse(final_df$Year_2012>=-2 & final_df$Year_2012<=1, "2", ifelse(final_df$Year_2012>=-3, "3"))))
final_df$Dry_2012<-as.factor(final_df$Dry_2012)                                     

#2013
final_df$Dry_2013<-ifelse(final_df$Year_2013>=0 & final_df$Year_2013<=3, "0", ifelse(final_df$Year_2013>=-1 & final_df$Year_2013<=-0, "1", ifelse(final_df$Year_2013>=-2 & final_df$Year_2013<=-1, "2", ifelse(final_df$Year_2013>=-3, "3"))))
final_df$Dry_2013<-as.factor(final_df$Dry_2013)                                 


#WET 
#-3-0= "0" (no drought), 0-1= "1" (wet), 1-2= "2" (more wet), 2-3= "3" (most wet)

#2009
final_df$Wet_2009<-ifelse(final_df$Year_2009>=-3 & final_df$Year_2009<=0, "0", ifelse(final_df$Year_2009>=0 & final_df$Year_2009<=1, "1", ifelse(final_df$Year_2009>=1 & final_df$Year_2009<=2, "2", ifelse(final_df$Year_2009>=2 & final_df$Year_2009<=3, "3", NA))))
final_df$Wet_2009<-as.factor(final_df$Wet_2009)

#2010
final_df$Wet_2010<-ifelse(final_df$Year_2010>=-3 & final_df$Year_2010<=0, "0", ifelse(final_df$Year_2010>=0 & final_df$Year_2010<=1, "1", ifelse(final_df$Year_2010>=1 & final_df$Year_2010<=2, "2", ifelse(final_df$Year_2010>=2 & final_df$Year_2010<=3, "3", NA))))
final_df$Wet_2010<-as.factor(final_df$Wet_2010)  

#2011
final_df$Wet_2011<-ifelse(final_df$Year_2011>=-3 & final_df$Year_2011<=0, "0", ifelse(final_df$Year_2011>=0 & final_df$Year_2011<=1, "1", ifelse(final_df$Year_2011>=1 & final_df$Year_2011<=2, "2", ifelse(final_df$Year_2011>=2 & final_df$Year_2011<=3, "3", NA))))
final_df$Wet_2011<-as.factor(final_df$Wet_2011)                               

#2012 
final_df$Wet_2012<-ifelse(final_df$Year_2012>=-3 & final_df$Year_2012<=0, "0", ifelse(final_df$Year_2012>=0 & final_df$Year_2012<=1, "1", ifelse(final_df$Year_2012>=1 & final_df$Year_2012<=2, "2", ifelse(final_df$Year_2012>=2 & final_df$Year_2012<=3, "3", NA))))
final_df$Wet_2012<-as.factor(final_df$Wet_2012)   

#2013
final_df$Wet_2013<-ifelse(final_df$Year_2013>=-3 & final_df$Year_2013<=0, "0", ifelse(final_df$Year_2013>=0 & final_df$Year_2013<=1, "1", ifelse(final_df$Year_2013>=1 & final_df$Year_2013<=2, "2", ifelse(final_df$Year_2013>=2 & final_df$Year_2013<=3, "3", NA))))
 final_df$Wet_2013<-as.factor(final_df$Wet_2013)   
```

